version: '3.8'

services:
  fpm_1:
    image: laravel_fpm_1
    deploy:
      replicas: 2
    volumes:
      - ./:/var/www/html
  
  fpm_2:
    image: laravel_fpm_1
    deploy:
      replicas: 2
    volumes:
      - ./:/var/www/html

  nginx:
    image: laravel_nginx
    deploy:
      replicas: 1
    ports:
      - 80:80

networks:
  default:
    name: laravel